kind: Service
apiVersion: v1
metadata:
  name: testdemo-service
  namespace: default
spec:
  selector:
    app: demotest
  type: NodePort
  ports:
    - port: 80
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demotest
  namespace: default
  labels:
    app: demotest
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: demotest
  template:
    metadata:
      labels:
        app: demotest
    spec:
      imagePullSecrets:
      - name: aliyundocker
      containers:
      - name: demotest
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
          name: http
