kind: Service
apiVersion: v1
metadata:
  name: testdemo-service
spec:
  selector:
    app: demotest
  type: NodePort
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demotest
  labels:
    app: demotest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demotest
  template:
    metadata:
      labels:
        app: demotest
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: demotest
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8089